# Generated by Django 3.1.1 on 2020-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
