# Generated by Django 3.1.1 on 2020-10-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='bubble.profile'),
        ),
    ]
