# Generated by Django 3.1.1 on 2020-10-19 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0003_auto_20201019_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
