# Generated by Django 3.1.1 on 2020-10-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0004_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ftype',
        ),
    ]
