# Generated by Django 3.1.1 on 2020-10-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0005_remove_file_ftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bubble.profile'),
            preserve_default=False,
        ),
    ]
