# Generated by Django 3.1.1 on 2020-10-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0007_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('note_number', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('exclusive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20)),
                ('small_title', models.TextField(blank=True, default='')),
                ('months', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('note_letter', models.CharField(blank=True, default='', max_length=1)),
                ('note_text', models.TextField(blank=True, default='')),
                ('cells', models.IntegerField(default=1)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='bubble.vaccineage')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='bubble.vaccine')),
            ],
        ),
    ]
