# Generated by Django 3.1.1 on 2020-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0008_calendar_vaccine_vaccineage_vaccinedose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineage',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccineage',
            name='months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccineage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
