# Generated by Django 3.1.1 on 2020-10-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0009_auto_20201031_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='vaccineage',
            options={'ordering': ['order', 'id']},
        ),
    ]
