# Generated by Django 3.1.1 on 2020-10-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0010_auto_20201031_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bubble.vaccinedose'),
        ),
    ]
