# Generated by Django 3.1.1 on 2020-10-31 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0011_document_vaccine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.RemoveField(
            model_name='vaccinedose',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vaccinedose',
            name='vaccine',
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={},
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='exclusive',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='note',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='note_number',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='order',
        ),
        migrations.AlterField(
            model_name='document',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bubble.vaccine'),
        ),
        migrations.DeleteModel(
            name='VaccineAge',
        ),
        migrations.DeleteModel(
            name='VaccineDose',
        ),
    ]
