# Generated by Django 3.1.1 on 2020-11-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubble', '0012_auto_20201031_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='vaccine',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
